website/routes/cart_routes.py
"""
Module for handling cart-related routes and logic.
"""

from flask import Blueprint, render_template, request, redirect, session, url_for, flash

from website.decorators import login_required
from website.views.carts import (
    add_watch_to_cart, show_cart, delete_from_cart,
    decrease_item_quantity, increase_item_quantity
)

carts = Blueprint("carts", __name__)


@carts.route("/addcart", methods=["POST"])
@login_required
def add_cart():
    """
    Add a watch to the user's cart.

    Returns:
        str: Redirect URL.
    """
    watch_id = request.form.get("watch_id")
    user_id = session.get("user_id")

    if not watch_id:
        flash("Invalid watch ID.", category="error")
        return redirect(url_for("watches.watch_detail", watch_id=watch_id))

    if request.method == "POST":
        add_watch_to_cart(watch_id, user_id)

        return redirect(url_for("watches.watch_detail", watch_id=watch_id))

    return None

@carts.route("/shopping-cart", methods=["GET"])
@login_required
def shopping_cart():
    """
    Display the user's shopping cart.

    Returns:
        str: Rendered HTML content.
    """
    user_id = session.get("user_id")

    items, total_sum = show_cart(user_id)

    return render_template("checkout/cart.html", items=items, total_sum=total_sum)


@carts.route("/deleteitem/<int:watch_id>", methods=["POST"])
@login_required
def delete_item(watch_id):
    """
    Delete an item from the user's cart.

    Keyword arguments:
        watch_id (int): The ID of the watch to be deleted.
    
    Returns:
        str: Redirect URL.
    """
    user_id = session.get("user_id")
    delete_from_cart(watch_id, user_id)

    return redirect(url_for("carts.shopping_cart"))


@carts.route("/decrease_quantity",  methods=["POST"])
@login_required
def decrease_quantity():
    """
    Decrease the quantity of an item in the user's cart.

    Returns:
        str: Redirect URL.
    """
    watch_id = request.form.get("watch_id")
    quantity = request.form.get("quantity")
    user_id = session.get("user_id")

    decrease_item_quantity(watch_id, quantity, user_id)

    return redirect(url_for("carts.shopping_cart"))


@carts.route("/increase_quantity",  methods=["POST"])
@login_required
def increase_quantity():
    """
    Increase the quantity of an item in the user's cart.

    Returns:
        str: Redirect URL.
    """
    watch_id = request.form.get("watch_id")
    user_id = session.get("user_id")

    increase_item_quantity(watch_id, user_id)

    return redirect(url_for("carts.shopping_cart"))

website/routes/watch_routes.py
"""
Module for handling routes related to watches.
"""

from flask import Blueprint, render_template, request, session, flash, redirect, url_for

from website.decorators import login_required

from website.views.watches import get_all_watches, get_watch_detail, add_review, delete_watch_review


watches = Blueprint("watches", __name__)


@watches.route("/")
def all_watches():
    """
    Render the page displaying all watches.

    Returns:
        str: Rendered HTML content.
    """
    watches_data = get_all_watches()
    return render_template(
        "watches/watches.html",
        watches=watches_data[0],
        page=watches_data[1],
        items_per_page=watches_data[2],
        total_pages=watches_data[3]
    )


@watches.route("/watch/<int:watch_id>", methods=["GET", "POST"])
def watch_detail(watch_id):
    """
    Display details of a specific watch.

    Keyword arguments:
        watch_id (int): The ID of the watch.

    Returns:
        str: Rendered HTML content.
    """
    if request.method == "GET":
        details, reviews, average_rating, review_count = get_watch_detail(watch_id)
        return render_template(
            "watches/watch_detail.html",
            details=details,
            reviews=reviews,
            average_rating=average_rating,
            review_count=review_count
        )
    if request.method == "POST":
        if not session.get("user_id"):
            return redirect("/login")

        rating = request.form.get("ratings")
        description = request.form.get("description")
        user_id = session.get("user_id")

        if len(description) > 1000:
            flash("Review length exceeds 1000 characters!", category="error")
        elif len(description) == 0:
            flash("Review cannot be empty!", category="error")
        else:
            if add_review(watch_id, user_id, rating, description):
                flash("Review added!")
            else:
                flash("You have already reviewed this watch!", category="error")

        return redirect(url_for("watches.watch_detail", watch_id=watch_id))

    return None

@watches.route("/delete_review", methods=["POST"])
@login_required
def delete_review():
    """
    Delete a review.

    Returns:
        str: Redirect URL.
    """
    logged_in_user = session.get("user_id")
    review_id = request.form["review_id"]
    user_id = request.form["user_id"]
    if logged_in_user == int(user_id):
        delete_watch_review(review_id, user_id)
        flash("Review deleted successfully!", category="success")
    else:
        flash("You are not authorized to delete this review.", category="error")

    return redirect(request.referrer)

website/views/watches.py
"""
Module for implementing watch-related logic
"""

from datetime import date
from flask import request
from sqlalchemy.sql import text
from website.db import db


def get_all_watches():
    """
    Retrieve a paginated list of watches.

    Returns:
        A tuple containing a list of watches, current page number, items per page, and total pages.
    """
    page = int(request.args.get("page", 1))
    items_per_page = 6

    offset = (page - 1) * items_per_page

    total_items_query = db.session.execute(
        text("SELECT COUNT(*) FROM watches;"))
    total_items = total_items_query.fetchone()[0]

    total_pages = (total_items + items_per_page - 1) // items_per_page

    result = db.session.execute(
        text(
            "SELECT id, brand, model, cast(price as money) "
            "FROM watches ORDER BY brand LIMIT :limit OFFSET :offset;"
        ),
        {"limit": items_per_page, "offset": offset}
    )

    watches = result.fetchall()

    return watches, page, items_per_page, total_pages


def get_watch_detail(watch_id):
    """
    Get detailed information about a specific watch.

    Keyword arguments:
        id (int): The ID of the watch.

    Returns:
        tuple: A tuple containing details about the watch, its reviews, 
        average rating, and review count.
    """
    query = db.session.execute(text(
        "SELECT id, brand, model, cast(price as money), description "
        "FROM watches WHERE id=:watch_id;"
    ), {"watch_id": watch_id})
    details = query.fetchone()

    review_query = db.session.execute(text(
        "SELECT reviews.id as review_id, users.id as user_id, users.username, "
        "reviews.review, reviews.rating, reviews.review_date "
        "FROM reviews "
        "JOIN users ON reviews.user_id = users.id "
        "WHERE reviews.watch_id=:watch_id;"
    ), {"watch_id": watch_id})

    rating_query = db.session.execute(text(
        "SELECT ROUND(AVG(rating), 0) "
        "FROM reviews "
        "WHERE watch_id=:watch_id"), {"watch_id": watch_id})

    count_query = db.session.execute(
        text("SELECT COUNT(*) FROM reviews WHERE watch_id=:watch_id;"), {"watch_id": watch_id})
    review_count = count_query.fetchone()[0]

    average_rating = rating_query.fetchone()[0]

    reviews = review_query.fetchall()

    return details, reviews, average_rating, review_count


def add_review(watch_id, user_id, rating, description):
    """
    Add a review for a specific watch.

    Keyword arguments:
        watch_id (int): The ID of the watch.
        user_id (int): The ID of the user submitting the review.
        rating (int): The rating given to the watch.
        description (str): The review description.

    Returns:
        True if the review was added successfully, False otherwise.
    """
    today = date.today()

    query = """
    INSERT INTO reviews (watch_id, user_id, review, rating, review_date)
    SELECT :watch_id, :user_id, :review, :rating, :review_date
    WHERE NOT EXISTS (
        SELECT 1 FROM reviews 
        WHERE user_id = :user_id 
        AND watch_id = :watch_id
    )
    """

    result = db.session.execute(
        text(query),
        {
            "watch_id": watch_id,
            "user_id": user_id,
            "review": description,
            "rating": rating,
            "review_date": today
        }
    )
    db.session.commit()

    return result.rowcount > 0


def delete_watch_review(review_id, user_id):
    """
    Delete a user's review for a specific watch.

    Keyword arguments:
        review_id (int): The ID of the review to be deleted.
        user_id (int): The ID of the user who submitted the review.
    """
    db.session.execute(text("DELETE FROM reviews WHERE id=:review_id AND user_id=:user_id"), {
                       "review_id": review_id, "user_id": user_id})
    db.session.commit()

website/templates/watches/watch_detail.html
{% extends "base.html" %} {% block content %}

<div class="details-container">
  <div class="details-image">
    <img
      src="{{url_for('static', filename='static/images/watches/' ~ details.brand ~ '_' ~ details.model ~ '.png')}}"
    />
  </div>

  <div class="details-info">
    <h2 id="watch-name">{{ details.brand }} {{ details.model }}</h2>
    <h2 id="watch-price">{{ details.price }}</h2>
    {% if details.description %}
    <p class="details-description">{{ details.description }}</p>
    {% else %}
    <p>There is no description of this watch.</p>
    {% endif %} {% if session.user_id %}
    <form action="{{url_for('carts.add_cart')}}" method="POST">
      <input type="hidden" name="watch_id" value="{{ details.id }}" />
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <button>Add To Cart</button>
    </form>
    {% endif %}
  </div>
</div>

<div class="reviews-container">
  {% if reviews %}
  <h2>Reviews</h2>
  <div style="font-weight: bold">
    <span>Average rating of {{average_rating}}</span>
    {% for i in range(average_rating | int) %} &#9733; {% endfor %}
    <span>| by {{review_count}} reviews</span>
  </div>
  {% for review in reviews %}
  <hr />
  <div>
    <div>
      {% for i in range(review.rating) %} &#9733; {% endfor %}
      <span>{{ review.username }}</span>
      <span>&#183;</span>
      <span>{{ review.review_date }}</span>
    </div>
    <div class="review-text">{{ review.review }}</div>
    <div>
      {% if session.user_id == review.user_id %}
      <form method="POST" action="{{url_for('watches.delete_review')}}">
        <input type="hidden" name="review_id" value="{{ review.review_id }}" />
        <input type="hidden" name="user_id" value="{{ review.user_id }}" />
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <button id="delete-review" type="submit">Delete Review</button>
      </form>
      {% endif %}
    </div>
  </div>
  {% endfor %} {% else %}
  <p class="no-reviews">This watch doesn't have any reviews.</p>
  {% endif %} {% if session.user_id %}
  <div>
    <form method="POST">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div>
        <div class="description">
          <textarea
            placeholder="Write a review..."
            rows="5"
            name="description"
            id="description"
          ></textarea>
        </div>
        <div>
          <label for="ratings">Give rating</label>
          <select name="ratings" id="ratings">
            {% for rating in range(1, 6) %}
            <option>{{ rating }}</option>
            {% endfor %}
          </select>
        </div>
        <div><button type="submit">submit</button></div>
      </div>
    </form>
  </div>
  {% endif %}
</div>

{% endblock %}

website/templates/watches/watches.html
{% extends "base.html" %} {% block title %} Home {% endblock %} {% block content
%}
<div class="watches">
  {% for watch in watches %}
  <div class="watch-card">
    <div class="watch-image">
      <a href="{{ url_for('watches.watch_detail', watch_id=watch.id) }}">
        <img
          src="{{url_for('static', filename='static/images/watches/' ~ watch.
          brand ~ '_' ~ watch.model ~ '.png')}}"
        />
      </a>
    </div>
    <div class="watch-info">
      <p style="text-transform: uppercase">
        {{ watch.brand }} {{ watch.model }}
      </p>
      <p>{{ watch.price }}</p>
    </div>
  </div>
  {% endfor %}
</div>

<div class="pagination">
  {% for i in range(1, total_pages + 1) %} {% if i == page %}
  <span>{{ i }}</span>
  {% else %}
  <a href="{{ url_for('watches.all_watches', page=i) }}">{{ i }}</a>
  {% endif %} {% endfor %}
</div>
{% endblock %}