website/routes/cart_routes.py
"""
Module for handling cart-related routes and logic.
"""

from flask import Blueprint, render_template, request, redirect, session, url_for, flash

from website.decorators import login_required
from website.views.carts import (
    add_watch_to_cart, show_cart, delete_from_cart,
    decrease_item_quantity, increase_item_quantity
)

carts = Blueprint("carts", __name__)


@carts.route("/addcart", methods=["POST"])
@login_required
def add_cart():
    """
    Add a watch to the user's cart.

    Returns:
        str: Redirect URL.
    """
    watch_id = request.form.get("watch_id")
    user_id = session.get("user_id")

    if not watch_id:
        flash("Invalid watch ID.", category="error")
        return redirect(url_for("watches.watch_detail", watch_id=watch_id))

    if request.method == "POST":
        add_watch_to_cart(watch_id, user_id)

        return redirect(url_for("watches.watch_detail", watch_id=watch_id))

    return None

@carts.route("/shopping-cart", methods=["GET"])
@login_required
def shopping_cart():
    """
    Display the user's shopping cart.

    Returns:
        str: Rendered HTML content.
    """
    user_id = session.get("user_id")

    items, total_sum = show_cart(user_id)

    return render_template("checkout/cart.html", items=items, total_sum=total_sum)


@carts.route("/deleteitem/<int:watch_id>", methods=["POST"])
@login_required
def delete_item(watch_id):
    """
    Delete an item from the user's cart.

    Keyword arguments:
        watch_id (int): The ID of the watch to be deleted.
    
    Returns:
        str: Redirect URL.
    """
    user_id = session.get("user_id")
    delete_from_cart(watch_id, user_id)

    return redirect(url_for("carts.shopping_cart"))


@carts.route("/decrease_quantity",  methods=["POST"])
@login_required
def decrease_quantity():
    """
    Decrease the quantity of an item in the user's cart.

    Returns:
        str: Redirect URL.
    """
    watch_id = request.form.get("watch_id")
    quantity = request.form.get("quantity")
    user_id = session.get("user_id")

    decrease_item_quantity(watch_id, quantity, user_id)

    return redirect(url_for("carts.shopping_cart"))


@carts.route("/increase_quantity",  methods=["POST"])
@login_required
def increase_quantity():
    """
    Increase the quantity of an item in the user's cart.

    Returns:
        str: Redirect URL.
    """
    watch_id = request.form.get("watch_id")
    user_id = session.get("user_id")

    increase_item_quantity(watch_id, user_id)

    return redirect(url_for("carts.shopping_cart"))

website/routes/watch_routes.py
"""
Module for handling routes related to watches.
"""

from flask import Blueprint, render_template, request, session, flash, redirect, url_for

from website.decorators import login_required

from website.views.watches import get_all_watches, get_watch_detail, add_review, delete_watch_review


watches = Blueprint("watches", __name__)


@watches.route("/")
def all_watches():
    """
    Render the page displaying all watches.

    Returns:
        str: Rendered HTML content.
    """
    watches_data = get_all_watches()
    return render_template(
        "watches/watches.html",
        watches=watches_data[0],
        page=watches_data[1],
        items_per_page=watches_data[2],
        total_pages=watches_data[3]
    )


@watches.route("/watch/<int:watch_id>", methods=["GET", "POST"])
def watch_detail(watch_id):
    """
    Display details of a specific watch.

    Keyword arguments:
        watch_id (int): The ID of the watch.

    Returns:
        str: Rendered HTML content.
    """
    if request.method == "GET":
        details, reviews, average_rating, review_count = get_watch_detail(watch_id)
        return render_template(
            "watches/watch_detail.html",
            details=details,
            reviews=reviews,
            average_rating=average_rating,
            review_count=review_count
        )
    if request.method == "POST":
        if not session.get("user_id"):
            return redirect("/login")

        rating = request.form.get("ratings")
        description = request.form.get("description")
        user_id = session.get("user_id")

        if len(description) > 1000:
            flash("Review length exceeds 1000 characters!", category="error")
        elif len(description) == 0:
            flash("Review cannot be empty!", category="error")
        else:
            if add_review(watch_id, user_id, rating, description):
                flash("Review added!")
            else:
                flash("You have already reviewed this watch!", category="error")

        return redirect(url_for("watches.watch_detail", watch_id=watch_id))

    return None

@watches.route("/delete_review", methods=["POST"])
@login_required
def delete_review():
    """
    Delete a review.

    Returns:
        str: Redirect URL.
    """
    logged_in_user = session.get("user_id")
    review_id = request.form["review_id"]
    user_id = request.form["user_id"]
    if logged_in_user == int(user_id):
        delete_watch_review(review_id, user_id)
        flash("Review deleted successfully!", category="success")
    else:
        flash("You are not authorized to delete this review.", category="error")

    return redirect(request.referrer)

website/views/carts.py
"""
Module for handling cart-related logic.
"""

from flask import flash
from sqlalchemy.sql import text
from website.db import db


def add_watch_to_cart(watch_id, user_id):
    """
    Add a watch to the user's cart.

    Keyword arguments:
        watch_id (int): The ID of the watch to be added to the cart.
        user_id (int): The ID of the user.

    Returns:
        None
    """
    count = db.session.execute(
        text("SELECT COUNT(*) FROM cart WHERE watch_id=:watch_id AND user_id=:user_id"),
        {"watch_id": watch_id, "user_id": user_id}
    )
    count_result = count.fetchone()[0]
    if count_result == 0:
        query = "INSERT INTO cart (watch_id, user_id, quantity) values (:watch_id, :user_id, 1);"
        db.session.execute(
            text(query), {"watch_id": watch_id, "user_id": user_id})
        db.session.commit()
        flash("Watch added to cart!")

    else:
        db.session.execute(
            text(
                "UPDATE cart SET quantity = quantity + 1 "
                "WHERE watch_id=:watch_id AND user_id=:user_id"
            ),
            {"watch_id": watch_id, "user_id": user_id}
        )
        db.session.commit()
        flash("Item updated")


def show_cart(user_id):
    """
    Retrieve the user's cart.

    Keyword arguments:
        user_id (int): The ID of the user.

    Returns:
        tuple: A tuple containing a list of items in the cart and
        the total sum of prices.
    """
    query = db.session.execute(text(
        "SELECT c.watch_id, c.quantity, w.brand, w.model, cast(w.price as money), "
        "cast(SUM(w.price * c.quantity) as money) as total_price "
        "FROM cart c JOIN watches w ON c.watch_id = w.id "
        "WHERE c.user_id=:user_id "
        "GROUP BY c.watch_id, c.quantity, w.brand, w.model, w.price;"),
        {"user_id": user_id})

    total_sum_query = db.session.execute(text(
        "SELECT cast(SUM(w.price * c.quantity) as money) as total_sum "
        "FROM cart c JOIN watches w ON c.watch_id = w.id "
        "WHERE c.user_id=:user_id;"),
        {"user_id": user_id})

    items = query.fetchall()
    total_sum = total_sum_query.fetchone()[0]

    return items, total_sum


def delete_from_cart(watch_id, user_id):
    """
    Delete a watch from the user's cart.

    Keyword arguments:
        watch_id (int): The ID of the watch to be removed from the cart.
        user_id (int): The ID of the user.
    Returns:
        None
    """
    db.session.execute(text("DELETE FROM cart WHERE watch_id=:watch_id AND user_id=:user_id"), {
                       "watch_id": watch_id, "user_id": user_id})
    db.session.commit()


def decrease_item_quantity(watch_id, quantity, user_id):
    """
    Decrease the quantity of a watch in the user's cart.

    Keyword arguments:
        watch_id (int): The ID of the watch.
        quantity (int): The current quantity of the watch.
        user_id (int): The ID of the user.

    Returns:
        None
    """
    if int(quantity) == 1:
        db.session.execute(text("DELETE FROM cart WHERE watch_id=:watch_id AND user_id=:user_id"), {
                           "watch_id": watch_id, "user_id": user_id})
        db.session.commit()
    else:
        db.session.execute(text(
            "UPDATE cart SET quantity = quantity - 1 WHERE watch_id=:watch_id"),
            {"watch_id": watch_id})
        db.session.commit()


def increase_item_quantity(watch_id, user_id):
    """
    Increase the quantity of a watch in the user's cart.

    Keyword arguments:
        watch_id (int): The ID of the watch.
        user_id (int): The ID of the user.

    Returns:
        None
    """
    db.session.execute(
        text(
            "UPDATE cart SET quantity = quantity + 1 "
            "WHERE watch_id=:watch_id AND user_id=:user_id"
        ),
        {"watch_id": watch_id, "user_id": user_id}
    )
    db.session.commit()

website/views/checkout.py
"""
Module for handling checkout-related logic.
"""

from datetime import date
from flask import session
from sqlalchemy.sql import text
from website.db import db


def get_cart_items(user_id):
    """
    Retrieve cart items for the user.

    Keyword arguments:
        user_id (int): User's ID.

    Returns:
        list: List of tuples containing (watch_id, quantity).
    """
    cart_query = db.session.execute(text(
        "SELECT watch_id, quantity FROM cart WHERE user_id=:user_id;"), {"user_id": user_id})
    return cart_query.fetchall()


def clear_cart(user_id):
    """
    Remove items from the cart after checkout.

    Keyword arguments:
        user_id (int): User's ID.

    Returns:
        None
    """
    db.session.execute(text("DELETE FROM cart WHERE user_id=:user_id;"), {"user_id": user_id})
    db.session.commit()


def create_order(user_id, watch_id, first_name, last_name, shipping_address, billing_address, phone_number, email, quantity, payment_method, order_date):
    """
    Create a new order in the database.

    Keyword arguments:
        user_id (int): User's ID.
        watch_id (int): Watch ID.
        first_name (str): User's first name.
        last_name (str): User's last name.
        shipping_address (str): User's shipping address.
        billing_address (str): User's billing address.
        phone_number (str): User's phone number.
        email (str): User's email address.
        quantity (int): Quantity of the item.
        payment_method (str): Payment method used for the order.
        order_date (date): Order date.

    Returns:
        None
    """
    query = (
        "INSERT INTO orders (user_id, watch_id, first_name, last_name, "
        "shipping_address, billing_address, phone_number, email, "
        "quantity, payment_method, order_date) "
        "VALUES (:user_id, :watch_id, :first_name, :last_name, "
        ":shipping_address, :billing_address, :phone_number, "
        ":email, :quantity, :payment_method, :order_date);"
    )
    db.session.execute(
        text(query),
        {
            "user_id": user_id,
            "watch_id": watch_id,
            "first_name": first_name,
            "last_name": last_name,
            "shipping_address": shipping_address,
            "billing_address": billing_address,
            "phone_number": phone_number,
            "email": email,
            "quantity": quantity,
            "payment_method": payment_method,
            "order_date": order_date
        }
    )
    db.session.commit()


def checkout_items(first_name, last_name, shipping_address, billing_address, phone_number, email, payment_method):
    """
    Checkout items and create orders in the database.

    Keyword arguments:
        first_name (str): User's first name.
        last_name (str): User's last name.
        shipping_address (str): User's shipping address.
        billing_address (str): User's billing address.
        phone_number (str): User's phone number.
        email (str): User's email address.
        payment_method (str): Payment method used for the order.

    Returns:
        None
    """
    user_id = session.get("user_id")
    order_date = date.today()

    if all([
        first_name,
        last_name,
        shipping_address,
        billing_address,
        phone_number,
        email,
        payment_method
    ]):
        cart_items = get_cart_items(user_id)

        if cart_items:
            clear_cart(user_id)

            for item in cart_items:
                watch_id, quantity = item
                create_order(
                    user_id,
                    watch_id,
                    first_name,
                    last_name,
                    shipping_address,
                    billing_address,
                    phone_number,
                    email,
                    quantity,
                    payment_method,
                    order_date
                )

website/templates/checkout/cart.html
{% extends "base.html" %} {% block title %}Cart{% endblock %} {% block content
%} {% if items|length != 0 %}
<div class="small-container cart-page">
  <table>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>Subtotal</th>
    </tr>
    {% for item in items %}
    <tr>
      <td>
        <div class="cart-info">
          <div class="cart-image">
            <a href="{{ url_for('watches.watch_detail', watch_id=item[0]) }}">
              <img
                src="{{url_for('static', filename='static/images/watches/' ~ item[2] ~ '_' ~ item[3] ~ '.png')}}"
              />
            </a>
          </div>
          <div>
            <p style="text-transform: uppercase">
              {{item.brand}} {{item.model}}
            </p>
            <small>{{ item.price }}</small>
            <br />
            <form
              action="{{ url_for('carts.delete_item', watch_id=item.watch_id)}}"
              method="POST"
            >
              <input
                type="hidden"
                name="csrf_token"
                value="{{ csrf_token() }}"
              />
              <button id="removeButton">Remove</button>
            </form>
          </div>
        </div>
      </td>
      <td>
        <div style="display: flex; align-items: center">
          <form action="{{url_for('carts.decrease_quantity')}}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <input type="hidden" name="watch_id" value="{{ item.watch_id }}" />
            <input type="hidden" name="quantity" value="{{ item.quantity }}" />
            <button id="decrease">-</button>
          </form>
          <span id="quantity">{{item.quantity}}</span>
          <form action="{{url_for('carts.increase_quantity')}}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <input type="hidden" name="watch_id" value="{{ item.watch_id }}" />
            <input type="hidden" name="quantity" value="{{ item.quantity }}" />
            <button id="increase">+</button>
          </form>
        </div>
      </td>
      <td>{{item.total_price}}</td>
    </tr>
    {% endfor %}
  </table>
  <div>
    <p><b>{{total_sum}}</b></p>
    <a id="checkout" href="/checkout">Proceed to checkout</a>
  </div>
</div>
{% else %}

<div class="empty-cart">
  <h2>Your cart is empty!</h2>
  <img src="{{url_for('static', filename='static/images/misc/cart.png')}}" />
  <a href="{{ url_for('watches.all_watches')}}">
    <button>Continue shopping</button>
  </a>
</div>
{% endif %} {% endblock %}

website/templates/checkout/checkout.html
{% extends "base.html" %} {% block title %} Checkout {% endblock %} {% block
content %}

<div class="checkout-page">
  <form method="POST" id="checkoutForm">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <h2>Fill in your information</h2>
    <div class="checkout-names">
      <div>
        <input
          type="text"
          placeholder="First name"
          required
          name="first_name"
        />
      </div>
      <div>
        <input type="text" placeholder="Last name" required name="last_name" />
      </div>
    </div>
    <div class="checkout-address">
      <div>
        <input
          type="text"
          placeholder="Shipping address"
          name="shipping_address"
          required
        />
      </div>
      <div>
        <input
          type="text"
          placeholder="Billing address"
          name="billing_address"
          required
        />
      </div>
    </div>
    <div class="checkout-contact">
      <div>
        <input
          type="tel"
          placeholder="Phone number"
          name="phone_number"
          required
        />
      </div>
      <div>
        <input type="email" placeholder="Email" name="email" required />
      </div>
    </div>
    <h2>Select payment method</h2>
    <div class="payment-method payment-container">
      <div>
        <input type="radio" id="paypal" name="payment" value="paypal" />
        <label for="paypal">
          <img
            src="{{url_for('static', filename='static/images/payment/paypal.png')}}"
            width="80"
            height="80"
        /></label>
      </div>
      <div>
        <input type="radio" id="googlepay" name="payment" value="googlepay" />
        <label for="googlepay">
          <img
            src="{{url_for('static', filename='static/images/payment/google-pay.png')}}"
            width="50"
            height="50"
        /></label>
      </div>
      <div>
        <input
          type="radio"
          id="credit-card"
          name="payment"
          value="credit-card"
        />
        <label for="credit-card">
          <img
            src="{{url_for('static', filename='static/images/payment/mastercard.png')}}"
            width="50"
            height="50"
        /></label>
      </div>
      <div>
        <input
          type="radio"
          id="bank-transfer"
          name="payment"
          value="bank-transfer"
        />
        <label for="bank-transfer">
          <img
            src="{{url_for('static', filename='static/images/payment/skrill.png')}}"
            width="50"
            height="50"
        /></label>
      </div>
    </div>
    <div class="place-order">
      <button type="submit">Place order</button>
    </div>
  </form>
  <script src="{{ url_for('static', filename='static/js/checkout.js') }}"></script>
</div>

{% endblock %}