website/admin/views/users.py
"""
Module for handling user-related logic for admin panel.
"""

from sqlalchemy.sql import text

from website.db import db


def users_page():
    """
    Retrieve information about all users.

    Returns:
        list: A list of user records.
    """
    query = db.session.execute(
        text("SELECT id, username, privileges FROM users;"))

    users = query.fetchall()

    return users


def remove_user(user_id):
    """
    Remove a user from the database.

    Keyword arguments:
        user_id (int): The ID of the user to be removed.

    Returns:
        None
    """

    db.session.execute(text("DELETE FROM users WHERE id=:user_id"), {
                       "user_id": user_id})
    db.session.commit()

website/routes/profile_routes.py
"""This module defines routes related to user profiles."""

from flask import Blueprint, render_template, redirect, flash, session, url_for
from website.decorators import login_required

from  website.views.profile import show_profile_data, delete_profile_data

profile = Blueprint("profile", __name__)


@profile.route("/profile", methods=["GET"])
@login_required
def show_profile():
    """
    Display the user's profile page.

    Returns:
        str: Rendered HTML content.
    """
    user_id = session.get("user_id")

    username, orders_data = show_profile_data(user_id)

    return render_template("user/profile.html", username=username, orders=orders_data)


@profile.route("/profile", methods=["POST"])
@login_required
def delete_profile():
    """
    Delete the user's profile.

    Returns:
        str: Redirect URL after deletion.
    """
    user_id = session.get("user_id")

    delete_profile_data(user_id)

    flash("Account deleted!", category="success")

    return redirect(url_for("auth.logout"))

website/views/profile.py
"""
Module for handling profile-related logic.
"""

from sqlalchemy.sql import text
from website.db import db


def show_profile_data(user_id):
    """
    Retrieve profile data for a given user.

    Keyword arguments:
        user_id (int): The ID of the user.

    Returns:
        tuple: A tuple containing the username and a list of order data.
    """
    user_query = db.session.execute(
        text("SELECT username FROM users WHERE id=:user_id"), {"user_id": user_id})
    username = user_query.fetchone()[0]

    order_query = db.session.execute(text(
        "SELECT watch_id, brand, model, cast(price as money), quantity, order_date "
        "FROM orders "
        "JOIN watches ON orders.watch_id = watches.id "
        "WHERE orders.user_id = :user_id "
        "ORDER BY order_date"), {"user_id": user_id})
    orders_data = order_query.fetchall()

    return username, orders_data


def delete_profile_data(user_id):
    """
    Delete a user's profile.

    Keyword arguments:
        user_id (int): The ID of the user.
    """
    db.session.execute(text("DELETE FROM users WHERE id=:user_id"), {
                       "user_id": user_id})
    db.session.commit()

website/templates/user/profile.html
{% extends "base.html" %} {% block title %} Profile {% endblock %} {% block
content %}
<div class="profile-page">
  <div class="profile-data">
    <h1>{{username}}</h1>
    <form
      id="deleteProfile"
      action="{{url_for('profile.delete_profile')}}"
      method="POST"
    >
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <button type="button" onclick="DeleteConfirm(this.form)">
        Delete Account
      </button>
    </form>
  </div>
  <div class="profile-orders">
    {% if orders %}
    <table class="profile-table">
      <caption>
        Your orders
      </caption>
      <thead>
        <tr>
          <th scope="col">Watch</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Date Of Order</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}

        <tr>
          <td data-label="Watch">
            <a
              href="{{ url_for('watches.watch_detail', watch_id=order.watch_id) }}"
              >{{order.brand}} {{order.model}}</a
            >
          </td>
          <td data-label="Price">{{order.price}}</td>
          <td data-label="Quantity">{{order.quantity}}</td>
          <td data-label="Order Date">{{order.order_date}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <h2>You don't have any orders!</h2>
    {% endif %}
  </div>
</div>
<script src="{{ url_for('static', filename='static/js/profile.js') }}"></script>
{% endblock %} /* */